services:
  - type: web
    name: etf-screener
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/puppeteer
